# Docker Compose configuration for monitoring services
services:
  ggcache:
    image: ggcache:latest
    container_name: ggcache
    ports:
      - "9999:9999"
      - "10000:10000"
      - "10001:10001"
      - "2222:2222"
      - "2223:2223"
      - "2224:2224"
      - "6060:6060"
      - "6061:6061"
      - "6062:6062"
      - "2379:2379"
      - "22379:22379"
      - "32379:32379"
    depends_on:
      - mysql
      - prometheus
      - grafana
    networks:
      - monitoring
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ggcache

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/ggcache.json
    depends_on:
      - prometheus
    networks:
      - monitoring

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ggcache
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring

networks:
  monitoring:
    name: ggcache-301_monitoring
    external: true

volumes:
  mysql_data:
  prometheus_data:
  grafana_data: