global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ggcache'
    static_configs:
      - targets: 
        - 'localhost:2112'  # 节点1
        - 'localhost:2113'  # 节点2
        - 'localhost:2114'  # 节点3
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: 'localhost:(\d+)'
        replacement: 'node_${1}'  # 将端口号作为节点标识
