mysql:
    driverName: mysql
    host: localhost
    port: 3306
    database: kv
    username: root
    password: 1234
    charset: utf8mb4

etcd:
    address: 
        - localhost:2379
        - localhost:22379
        - localhost:32379
    ttl: 5

services:
    gateway:
        name: gateway
        loadBalance: true
        addr:
            - localhost:10005
    student:
        name: student
        loadBalance: false
        addr: 
            - localhost:10006
    groupcache:
        name: GroupCache
        addr:
            - localhost:9999
            - localhost:10000
            - localhost:10001

domain:
    student:
        name: student
    groupcache:
        name: GroupCache
